apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  selector:
    app: webapp  # This should match the label of the deployment pod
  ports:
    - protocol: TCP
      port: 80          # Port exposed inside the cluster
      targetPort: 8082   # Port inside the container (matches your Docker container port)
  type: LoadBalancer    # Use 'ClusterIP' for internal-only service, 'LoadBalancer' for external access
